feedback_form/blueprints/feedback/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    url_for,
    render_template
)

from flask_login import (
    current_user,
    login_required)

from feedback_form.blueprints.user.decorators import anonymous_required
from feedback_form.blueprints.user.models import User

from feedback_form.blueprints.feedback.forms import FeedbackForm, ContactForm
from feedback_form.extensions import mail, db
from feedback_form.blueprints.feedback.models import Review, Employee

feedback = Blueprint('feedback', __name__, template_folder='templates')


@feedback.route('/feedback', methods=['GET', 'POST'])
@login_required
def index():
    """
    Endpoint to handle feedback form submissions.

    :return: Rendered template or redirect to success page upon successful
             submission.
    """
    form = FeedbackForm()

    """ fetch employees from database"""
    employees = Employee.query.all()

    employee_data = [(str(employee.id),
                      employee.employee_name) for employee in employees]

    form.employee_feedback.choices = employee_data

    if form.validate_on_submit():
        """ to avoid circular imports """

        user_email = current_user.email

        employee_id = form.employee_feedback.data
        service_feedback = form.service_feedback.data
        additional_comments = form.additional_comments.data

        # Fetch the selected employee
        selected_employee = Employee.query.get(int(employee_id))

        # Create a Review instance and add it to the database
        review_entry = Review(
            employee_feedback=selected_employee.employee_name,
            service_feedback=service_feedback,
            additional_comments=additional_comments,
            employee=selected_employee
        )
        db.session.add(review_entry)
        db.session.commit()

        from feedback_form.blueprints.feedback.tasks import \
            deliver_feedback_email
        deliver_feedback_email(
                user_email,
                additional_comments,
                selected_employee.id,
                service_feedback)

        flash('Your feedback has been successfully submitted!', 'success')
        return redirect(url_for('page.success_page'))
    return render_template('feedback/index.html', form=form)


@feedback.route('/contact', methods=['GET', 'POST'])
@anonymous_required()
def contact():
    """
    Endpoint to handle contact form submissions.

    :return: Rendered template or redirect to success page upon successful
             submission.
    """
    form = ContactForm()

    if form.validate_on_submit():
        """send email on form submission"""
        from feedback_form.blueprints.feedback.tasks import \
            deliver_contact_email
        deliver_contact_email(request.form.get("name"),
                              request.form.get("email"),
                              request.form.get("message")
                              )
        flash('Your message has been successfully sent!', 'success')
        return redirect(url_for('page.success_page'))

    return render_template('feedback/contact.html', form=form)

feedback_form/blueprints/page/views.py
from flask import Blueprint, render_template


page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    """
    Endpoint to render the home page.

    :return: Rendered template for the home page.
    """
    return render_template('page/home.html')


@page.route('/success')
def success_page():
    """
    Endpoint to render the success page.

    :return: Rendered template for the success page.
    """
    return render_template('page/success.html')


@page.route('/about')
def about_us():
    return render_template('page/about.html')

feedback_form/blueprints/user/views.py
#!/usr/bin/python3
"""Module defining view functions for user login"""
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    session,
    render_template)

from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

# custom libraries and modules
from lib.safe_next_url import safe_next_url
from feedback_form.blueprints.user.decorators import anonymous_required
from feedback_form.blueprints.user.models import User
from feedback_form.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignUpForm,
    WelcomeForm,
    UpdateCredentials)

user = Blueprint("user", __name__, template_folder="templates")


@user.route("/login", methods=["GET", "POST"])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get("next"))

    if form.is_submitted() and form.validate():
        u = User.find_by_identity(request.form.get("identity"))

        if u and u.authenticated(password=request.form.get("password")):
            remember = request.form.get("remember", False)
            if login_user(u, remember=remember) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get("next")
                if next_url:
                    return redirect(safe_next_url(next_url))
                return redirect(url_for("user.settings"))

            else:
                flash("This account has been disabled.", "error")

        else:
            flash("Identity or password is incorrect.", "error")

    return render_template("user/login.html", form=form)


@user.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash("You have been logged out.", "success")
    return redirect(url_for("user.login"))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    # if form.validate_on_submit():
    if form.is_submitted() and form.validate():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    # if form.validate_on_submit():
    if form.is_submitted() and form.validate():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignUpForm()

    # if form.validate_on_submit():
    if form.is_submitted() and form.validate():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        session['signup_user'] = {'id': u.id, 'username': None}

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()
    # if form.validate_on_submit():
    if form.is_submitted() and form.validate():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    # if form.validate_on_submit():
    if form.is_submitted() and form.validate():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

feedback_form/templates/app.html
{% extends "base.html" %}

{% block title %}{% endblock%}

{% block header %}
        <section id="nav-bar">                                                                                                                                                      
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{url_for( 'page.home' )}}"><span class="feedback-color">FEEDBACK</span>FORM</a>
 
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navbarNav" aria-controls="navbarNav"
                  aria-expanded="false" aria-label="Toggle navigation">
                <!-- <span class="navbar-toggler-icon"></span> -->
                <i class="fa-solid fa-bars"></i>
              </button>
 
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{url_for( 'page.home' )}}">HOME</a>
                  </li>
                  <!--  <ul class="nav navbar-nav navbar-rigt"> -->
                    {% if current_user.role == "admin" %}
                    <!-- <li> -->
                        {% include "admin/_menu.html" %}
                        <!-- </li> -->
                    {% endif %}
                    <!-- </ul> -->
                  {% if current_user.is_authenticated %}
                    <!-- <li class="dropdown">                                                                                                                                       
                        <a href="#" class="dropdown-toggle"
                          data-toggle="dropdown"
                          role="button" aria-haspopup="true"
                          aria-expanded="false">Account
                          <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Session</li>
                            <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
                        </ul>
                    </li> -->
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        ACCOUNT
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li><a class="dropdown-item" href="{{ url_for('user.settings') }}">Settings</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('user.logout') }}">Log Out</a></li>
                        <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                      </ul>
                    </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">LOG IN</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.signup') }}">SIGN UP</a>
                  </li>
                  {% endif %}
                </ul>
<!--
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'feedback.index' )}}">FEEDBACK</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'page.about_us' )}}">ABOUT US</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'feedback.contact' )}}">CONTACT</a>
                  </li>
                </ul>
-->
              </div>
            </div>
        </nav>                                                                                                                                                                  
    </section>
{% endblock %}


<!-- {% block footer %}
    <li class="nav-item">
        <a class="nav-link" href="{{url_for( 'feedback.index' )}}">FEEDBACK</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{url_for( 'page.about_us' )}}">ABOUT US</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{url_for( 'feedback.contact' )}}">CONTACT</a>
    </li>
{% endblock %} -->

feedback_form/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!------------------------adding css file to base template using url_for --------------->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block header %}{% endblock %}
    <!--
    <section id="nav-bar">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{url_for( 'page.home' )}}"><span class="feedback-color">FEEDBACK</span>FORM</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navbarNav" aria-controls="navbarNav"
                  aria-expanded="false" aria-label="Toggle navigation">
    -->
                <!-- <span class="navbar-toggler-icon"></span> -->
    <!--            
                <i class="fa-solid fa-bars"></i>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{url_for( 'page.home' )}}">HOME</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'feedback.index' )}}">FEEDBACK</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'page.about_us' )}}">ABOUT US</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for( 'feedback.contact' )}}">CONTACT</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </section>
    -->

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="alert alert-success" role="alert">
                {% for category, message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% block body %} {% endblock %}
<!----------------------------footer section-------------------------------------->
<footer class="footer">
    <div class="container text-center">
        <ul class="list-inline">
            <li>© 2023 Your Company. All rights reserved.</li>
            <!-- {% block footer %}{% endblock %} -->
        </ul>
    </div>
    <div class="footer-icons text-center">
        <a href="https://www.facebook.com/yourcompany" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
        <a href="https://twitter.com/yourcompany" target="_blank"><i class="fab fa-twitter fa-lg"></i></a>
        <a href="https://www.instagram.com/yourcompany" target="_blank"><i class="fab fa-instagram fa-lg"></i></a>
        <a href="https://www.linkedin.com/company/yourcompany" target="_blank"><i class="fab fa-linkedin-in fa-lg"></i></a>
      </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
</body>
</html> 

feedback_form/templates/login.html
{% extends 'base.html' %}

{% block header %}
    <a src="{{ url_for('page.home') }}"
        class="img-responsive center-block md-margin-bottom"
        width="178" height="176" title="FeedBack Form" alt="Feedback Form"/>
    </a>
{% endblock %}

{% block footer %}
    <li><a href="{{ url_for('user.signup') }}">Sign up today</a></li>
{% endblock %}